onboarding = false

[keys]
previous_tab = "alt+i"
next_tab = "alt+o"
previous_workspace = "alt+shift+i"
next_workspace = "alt+shift+o"
reload_config = "prefix+shift+r"

[theme]
name = "tokyo-night"

[terminal]
default_shell = "fish"
new_cwd = "follow"
