# Get editor completions based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

### MAIN SHELL
# speed-first prompt: keep only the essentials
format = """
$username\
$hostname\
$directory\
$env_var\
$line_break\
$character"""
add_newline = true

[character]
# success_symbol = '[ﬦ](bold blue) '
# error_symbol = '[ﬦ](bold red) '
success_symbol = '[](bold blue)'
error_symbol = '[](bold red)'
# success_symbol = "(fg:#1e1e2e bg:#1e1e2e)[](fg:#585b70 bg:#1e1e2e)[ ](fg:#b4befe bg:#585b70)[](fg:#585b70 bg:none) "
# error_symbol = "[](fg:#585b70 bg:#1e1e2e)[ ](fg:#f38ba8 bg:#585b70)[](fg:#585b70 bg:none) "



[directory]
style = 'fg:blue'
read_only = ' '
use_os_path_sep = false   # fuck windows :verynice:
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "../"

[directory.substitutions]
'.config' = ' '
'Projects' = ' '
'Desktop' = ' '
'Documents' = ' '
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '
'Workstuff' = ' '
'git-files' = ' '

[username]
show_always = true
style_user = "fg:green bold"
format = "[$user]($style)[@](fg:blue)"

[hostname]
ssh_only = false
# ssh_symbol = "🌐 "
format = "[$hostname]($style) "
style = "fg:red bold"

[sudo]
disabled = true
format = '\[[$symbol]($style)\] '
style = 'fg:red'
symbol = ''

[git_branch]
disabled = true

[git_status]
disabled = true
format = ' (\[[$all_status]($style)\])'
style = 'fg:bright-purple'

[env_var.GIT_BRANCH_PROMPT]
variable = 'GIT_BRANCH_PROMPT'
default = ''
format = '[$env_value]($style)'
style = 'fg:bright-purple'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[cmd_duration]
format = '\[[ﮫ $duration]($style)\] '

[fill]
symbol = '─'
style = 'fg:black'

### LANGUAGE VERSION INDICATORS
[c]
format = ' \[[$symbol($version(-$name))]($style)\] '

[cmake]
format = ' \[[$symbol($version)]($style)\] '

[cobol]
format = '\[[$symbol($version)]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'

[crystal]
format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'

[deno]
format = '\[[$symbol($version)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '\[[$symbol($version)]($style)\]'

[erlang]
format = '\[[$symbol($version)]($style)\]'

[golang]
symbol = ' '
format = ' \[[$symbol($version)]($style)\] '

[haskell]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[helm]
symbol = 'ﴱ '
format = '\[[$symbol($version)]($style)\]'

[java]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'
style = 'fg:white'

[julia]
format = '\[[$symbol($version)]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[lua]
symbol = ' '
format = ' \[[$symbol($version)]($style)\] '

[nim]
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
symbol = ' '
format = ' \[[$symbol($version)]($style)\] '
detect_extensions = []
style = 'green'

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[package]
symbol = ' '
format = ' \[[$symbol$version]($style)\] '
# style = '16'
style = 'fg:bright-cyan'

[perl]
format = '\[[$symbol($version)]($style)\]'

[php]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = ' \[[$symbol($version)]($style)\] '

[python]
symbol = ' '
format = ' \[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\] '

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[rust]
symbol = ''
format = ' \[[$symbol($version)]($style)\] '

[scala]
format = '\[[$symbol($version)]($style)\]'

[spack]
format = '\[[$symbol$environment]($style)\]'

[swift]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'

### CONTEXT INDICATORS
[aws]
symbol = '  '
# symbol = '   '
style = "fg:purple"
format = '[$symbol($profile )($style)(\($region\) )(\[$duration\] )]($style)'

[docker_context]
symbol = ' '
format = ' \[[$symbol$context]($style)\] '

[gcloud]
symbol = ' '
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[kubernetes]
symbol = ' '
format = '\[[$symbol($cluster/$namespace)]($style)\]'
disabled = false

[openstack]
symbol = ' '
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'
